USE [DCustomer]
GO

SET ANSI_PADDING OFF
GO

IF  EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME='City')
BEGIN
	ALTER TABLE [dbo].[City]  WITH CHECK ADD CONSTRAINT [FK_City_State] FOREIGN KEY([StateId])
		REFERENCES [dbo].[State] ([Id])
	
	ALTER TABLE [dbo].[City] CHECK CONSTRAINT [FK_City_State]
END
GO

IF  EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME='Contact')
BEGIN
	ALTER TABLE [dbo].[Contact]  WITH CHECK ADD  CONSTRAINT [FK_Contact_City] FOREIGN KEY([CityId])
		REFERENCES [dbo].[City] ([Id])

	ALTER TABLE [dbo].[Contact] CHECK CONSTRAINT [FK_Contact_City]
END
GO
 