USE [Customer]
GO

SET ANSI_PADDING OFF
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME='City' and CONSTRAINT_TYPE = 'FOREIGN KEY')
BEGIN
	ALTER TABLE BuyList DROP CONSTRAINT [FK_City_State]
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME='Contact' and CONSTRAINT_TYPE = 'FOREIGN KEY')
BEGIN
	ALTER TABLE BuyList DROP CONSTRAINT [FK_Contact_City]
END
GO
 