USE [DCustomer]
GO

SET ANSI_PADDING OFF
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME='City' and CONSTRAINT_TYPE = 'FOREIGN KEY')
BEGIN
	ALTER TABLE City DROP CONSTRAINT [FK_City_State]
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME='Contact' and CONSTRAINT_TYPE = 'FOREIGN KEY')
BEGIN
	ALTER TABLE Contact DROP CONSTRAINT [FK_Contact_City]
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME='ProjectContact' and CONSTRAINT_TYPE = 'FOREIGN KEY')
BEGIN
	ALTER TABLE ProjectContact DROP CONSTRAINT [FK_ProjectContact_Project]
	ALTER TABLE ProjectContact DROP CONSTRAINT [FK_ProjectContact_Contact]
END
GO

 